name: momo-store
services:
  frontend-build:
    container_name: frontend-build
    image: ${DOCKER_REGISTRY}/docker-project-frontend:latest
    volumes:
      - static:/app/dist
    depends_on:
      - backend
  
  backend:
    container_name: backend
    image: ${DOCKER_REGISTRY}/docker-project-backend:latest
    ports:
      - "8081:8081/tcp"
    networks:
      - default
    restart: always
    cap_drop:
      - ALL
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/health"]
      interval: 10s
      timeout: 3s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.1'
          memory: 128M

  nginx:
    container_name: nginx
    image: ${DOCKER_REGISTRY}/docker-project-nginx:latest
    ports:
      - "80:80/tcp"
    volumes:
      - static:/usr/share/nginx/html:ro
    depends_on:
      - backend
      - frontend-build
    networks:
      - default
    restart: always
    environment:
      - VUE_APP_API_URL=/api
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/momo-store/index.html"]
      interval: 10s
      timeout: 3s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.1'
          memory: 128M

volumes:
  static:
    driver: local

networks:
  default:
    driver: bridge
