services:
  frontend-build:
    container_name: frontend-build
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - static:/app/dist
    depends_on:
      - backend
  
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8081:8081/tcp"
    networks:
      - default
    restart: always

  nginx:
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "8000:80/tcp"
    volumes:
      - static:/usr/share/nginx/html:ro
    depends_on:
      - backend
      - frontend-build
    networks:
      - default
    restart: always
    

volumes:
  static:
    driver: local

networks:
  default:
    driver: bridge
