services:
  frontend-build:
    container_name: frontend-build
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - static:/app/dist
    depends_on:
      - backend
  
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8081:8081/tcp"
    networks:
      - default
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/health"]
      interval: 10s
      timeout: 3s
      retries: 3

  nginx:
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "8000:80/tcp"
    volumes:
      - static:/usr/share/nginx/html:ro
    depends_on:
      - backend
      - frontend-build
    networks:
      - default
    restart: always
    environment:
      - VUE_APP_API_URL=/api
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/momo-store/index.html"]
      interval: 10s
      timeout: 3s
      retries: 3

volumes:
  static:
    driver: local

networks:
  default:
    driver: bridge
